name: Auto EUserv

on:
  schedule:
    - cron: '0 0 25 * *'  # 每月25日UTC时间0:00也就是北京时间UTC+8上午8：00运行,通常会延迟半小时到1小时
  workflow_dispatch:

# 在全局强制开启 Node.js 24，直接压制并解决老旧 Action 的警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # 指定Python3.x

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      env:
        EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
        EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
        TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
        TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
      run: python Github_Action.py
